spring:
    jpa:
       hibernate:
          naming:
             physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          ddl-auto: update
    datasource:
       url: jdbc:mysql://localhost:3306/inventorydb?createDatabaseIfNotExist=true
       username: root
       password: 'abcd@123'
       driver-class-name: com.mysql.jdbc.Driver
       initialization-mode: never
